import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const IGNORED_DIRS = new Set([
	'node_modules',
	'.git',
	'.next',
	'.nuxt',
	'dist',
	'build',
	'coverage',
	'.cache',
	'vendor',
	'__pycache__',
]);

export function findAgentsFiles(cwd: string): string[] {
	const found: string[] = [];
	const home = os.homedir();

	// 1. Project-level (recursive, maxDepth=3, hidden dirs included, IGNORED_DIRS excluded)
	found.push(...findInDirectory(cwd));

	// 2. ~/.config/*/AGENTS.md
	const configDir = path.join(home, '.config');
	if (fs.existsSync(configDir) && fs.statSync(configDir).isDirectory()) {
		try {
			for (const entry of fs.readdirSync(configDir, { withFileTypes: true })) {
				if (entry.isDirectory()) {
					const agentsPath = path.join(configDir, entry.name, 'AGENTS.md');
					if (fs.existsSync(agentsPath)) {
						found.push(agentsPath);
					}
				}
			}
		} catch {
			// Permission denied
		}
	}

	// 3. ~/.cursor/AGENTS.md
	const cursorAgents = path.join(home, '.cursor', 'AGENTS.md');
	if (fs.existsSync(cursorAgents)) {
		found.push(cursorAgents);
	}

	// 4. ~/.claude/AGENTS.md
	const claudeAgents = path.join(home, '.claude', 'AGENTS.md');
	if (fs.existsSync(claudeAgents)) {
		found.push(claudeAgents);
	}

	// 5. ~/AGENTS.md
	const homeAgents = path.join(home, 'AGENTS.md');
	if (fs.existsSync(homeAgents)) {
		found.push(homeAgents);
	}

	return [...new Set(found)];
}

function findInDirectory(dir: string, maxDepth = 3, currentDepth = 0): string[] {
	if (currentDepth > maxDepth) return [];

	const found: string[] = [];
	const agentsPath = path.join(dir, 'AGENTS.md');

	if (fs.existsSync(agentsPath)) {
		found.push(agentsPath);
	}

	if (currentDepth < maxDepth) {
		try {
			for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
				if (entry.isDirectory() && !IGNORED_DIRS.has(entry.name)) {
					found.push(...findInDirectory(path.join(dir, entry.name), maxDepth, currentDepth + 1));
				}
			}
		} catch {
			// Permission denied
		}
	}

	return found;
}

const DLR_SECTION_MARKER = '## DLR — Decision Log & Reflect';

export function hasExistingDlrSection(filePath: string): boolean {
	const content = fs.readFileSync(filePath, 'utf-8');
	return content.includes(DLR_SECTION_MARKER);
}

export function appendDlrSection(filePath: string, snippet: string): void {
	const existing = fs.readFileSync(filePath, 'utf-8');
	const separator = existing.trimEnd().length > 0 ? '\n\n' : '';
	fs.writeFileSync(filePath, `${existing.trimEnd()}${separator}${snippet}\n`, 'utf-8');
}

export function createAgentsFile(filePath: string, snippet: string): void {
	const header = `<!-- Generated by dlr init. Copy this file or its content into your agent configuration (e.g., .cursorrules, .claude/CLAUDE.md, etc.) -->\n\n`;
	fs.writeFileSync(filePath, `${header}${snippet}\n`, 'utf-8');
}
